### ISSUE TITLE
Saving note

### ISSUE THREAD

**Issue by markphd** [Autophagy/aerende#1]
I'm curious to find out how to properly save a note. I tried `:wq`, `:x`, `:q!` but each time I return back to Notes list, I only see the title and tag but not the notes.

**Comment by autophagy** [comment]
@markphd Thats strange - it should be saved with `:wq`. I'll see if I can replicate it.

**Comment by markphd** [comment]
@autophagy It's been a while since I encountered the issue. I couldn't replicate it anymore. Everything is working fine! Thanks for checking.
